### ISSUE TITLE
Error in MiniZinc fzn-gecode: error while loading shared libraries: libQt5PrintSupport.so.5: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by giamp66** [MiniZinc/iminizinc#7]
I'm trying to run iminizinc but I get the following error:
Error in MiniZinc:
/opt/MiniZincIDE-2.2.1-bundle-linux/bin/fzn-gecode: error while loading shared libraries: libQt5PrintSupport.so.5: cannot open shared object file: No such file or directory

when in the first cell a put:
%load_ext iminizinc
I get 
 MiniZinc to FlatZinc converter, version 2.2.1, build 29527117
Copyright (C) 2014-2018 Monash University, NICTA, Data61

And when I check for file, the file is there:
! ls -Al /opt/MiniZincIDE-2.2.1-bundle-linux/lib/libQt5PrintSupport.so.5
-rw-r--r-- 1 root root 467312 Sep  6 05:02 /opt/MiniZincIDE-2.2.1-bundle-linux/lib/libQt5PrintSupport.so.5

**Comment by giamp66** [comment]
I must specify that I'm trying to run iminizinc inside docker 
whit this Dockerfile:
FROM jupyter/scipy-notebook
MAINTAINER Gianpaolo Galli "ggg"
USER root
RUN apt-get update && apt-get install -y curl && apt-get install -y libqt5gui5
RUN curl -s -L https://github.com/MiniZinc/MiniZincIDE/releases/download/2.2.1/MiniZincIDE-2.2.1-bundle-linux-x86_64.tgz | tar -C /opt -zx
ENV MZN_DIR=/opt/MiniZincIDE-2.2.1-bundle-linux
ENV PATH=$MZN_DIR/bin:$PATH
ENV PATH=$MZN_DIR/lib:$PATH
ENV PATH=$MZN_DIR/share:$PATH
RUN pip install --upgrade pip && \
    pip install -U iminizinc
USER $NB_UID

**Comment by Dekker1** [comment]
Hi,

It seems you have forgotten to add the library folder to the library path
in your dockerfile

ENV LD_LIBRARY_PATH=$MZN_DIR/lib:$LD_LIBRARY_PATH

Let us know if this solves your problem.

Cheers,
Jip

**Comment by giamp66** [comment]
It works like a Swiss clock! 
Problem solved!
Thank you very much.
